// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8caEENgBfm2ebZZIZp-oGZ_W77WkOyLA',
    appId: '1:1002117708430:web:4ced0002e361f2025ba7df',
    messagingSenderId: '1002117708430',
    projectId: 'rentapp-957fe',
    authDomain: 'rentapp-957fe.firebaseapp.com',
    storageBucket: 'rentapp-957fe.firebasestorage.app',
    measurementId: 'G-T4LWNVRQV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiMmKqp-E_FisnyS8UAtaxEYCjacofyKE',
    appId: '1:1002117708430:android:a2758df40b5099dd5ba7df',
    messagingSenderId: '1002117708430',
    projectId: 'rentapp-957fe',
    storageBucket: 'rentapp-957fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5mYvUCpfo3pKhy2wOEyI1u6I4F8eWrI4',
    appId: '1:1002117708430:ios:d1976fe5e512230b5ba7df',
    messagingSenderId: '1002117708430',
    projectId: 'rentapp-957fe',
    storageBucket: 'rentapp-957fe.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5mYvUCpfo3pKhy2wOEyI1u6I4F8eWrI4',
    appId: '1:1002117708430:ios:d1976fe5e512230b5ba7df',
    messagingSenderId: '1002117708430',
    projectId: 'rentapp-957fe',
    storageBucket: 'rentapp-957fe.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8caEENgBfm2ebZZIZp-oGZ_W77WkOyLA',
    appId: '1:1002117708430:web:06c1406cee6b59925ba7df',
    messagingSenderId: '1002117708430',
    projectId: 'rentapp-957fe',
    authDomain: 'rentapp-957fe.firebaseapp.com',
    storageBucket: 'rentapp-957fe.firebasestorage.app',
    measurementId: 'G-MBGJFGQKT0',
  );

}