// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tIfLg1ZyoMs3pc8-AG_gAs5xVgn-47w',
    appId: '1:989018014187:web:c01ceecf1fe69176e999ae',
    messagingSenderId: '989018014187',
    projectId: 'zalonidentalhub',
    authDomain: 'zalonidentalhub.firebaseapp.com',
    storageBucket: 'zalonidentalhub.appspot.com',
    measurementId: 'G-82DQJL0JKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIeexhnwPLdCA9683lD4bfGiE6qmKT-2E',
    appId: '1:989018014187:android:945a019591fa006ee999ae',
    messagingSenderId: '989018014187',
    projectId: 'zalonidentalhub',
    storageBucket: 'zalonidentalhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQUWIZG8Uxx_jCrD7vZid0FSluK2hW6G0',
    appId: '1:989018014187:ios:cfb5c53d6ebe5708e999ae',
    messagingSenderId: '989018014187',
    projectId: 'zalonidentalhub',
    storageBucket: 'zalonidentalhub.appspot.com',
    iosBundleId: 'com.example.zaloniDentalHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQUWIZG8Uxx_jCrD7vZid0FSluK2hW6G0',
    appId: '1:989018014187:ios:8e2374ce1ad22005e999ae',
    messagingSenderId: '989018014187',
    projectId: 'zalonidentalhub',
    storageBucket: 'zalonidentalhub.appspot.com',
    iosBundleId: 'com.example.zaloniDentalHub.RunnerTests',
  );
}
